# Generated by Django 4.1.7 on 2023-03-04 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicperformer',
            options={'ordering': ('name',), 'verbose_name': 'Музыкальный исполнитель', 'verbose_name_plural': 'Музыкальные исполнители'},
        ),
        migrations.AlterField(
            model_name='album',
            name='music_performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='api.musicperformer', verbose_name='Музыкальный исполнитель'),
        ),
    ]
